image: Ubuntu 

stack:
  jdk 11 

services:
  - docker

branches:
  only:
    - master  

build: off 

install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose up --build -d
  - sleep 15
  - docker ps
  - sleep 15
   - java -jar artifacts/app-deadline.jar &
   - chmod +x gradlew

build_script:
   - ./gradlew test --info -Dselenide.headless=true